---
title: "hw04"
author: "Sam Shepard"
date: "3/8/2021"
output: html_document
---
```{r}
#update R:
#install.packages("installr")
library(installr)
updateR()
```


```{r}
library(tidyverse)
library(dplyr)
library(haven) #to load .sav file
library(ggplot2)
```


```{r}
#set working directory to "hw-samanthashepard"
PhysioThesis_CLEAN <- read_sav(here::here("final_project", "data", "PhysioThesis_March_21_2020_CLEAN.sav"), na = c("NA", ""),
                               col_types = cols(
                                 "Cndtn" = col_character(),
                                 .default = col_guess()
                               )
                               
)
```
                              

```{r}
View(PhysioThesis_CLEAN)
ncol(PhysioThesis_CLEAN)
nrow(PhysioThesis_CLEAN)
```

```{r}
PhysioThesis_CLEAN %>% 
  mutate(Condition = as.character(Cndtn),
        
         )
```


```{r}
#Summary tables to make sure my main variables look normal
PhysioThesis_CLEAN_descriptives<-PhysioThesis_CLEAN %>%
  group_by("Condition") %>% 
  summarize(across(PerformanceSelfEsteem:PosImp),
            list (Mean = ~ mean(.x, na.rm = TRUE),
                SD = ~ sd(.x, na.rm = TRUE),
                Median = ~ median(.x, na.rm = TRUE),
                Min = ~ min(.x, na.rm = TRUE),
                Max = ~ max(.x, na.rm = TRUE)
      ))

```

```{r}
#Plot

# Scatterplot 8
ggplot(PhysioThesis_CLEAN) +
  aes(x = Cndtn, y = ChThCW3)+
  geom_boxplot()+
  geom_jitter()+
  theme_classic()+
  xlab("Condition") +ylab("Challenge-Threat Index")

```





